### ISSUE TITLE
Terraform-operator-crds: applyMethod behavior is wrong

### ISSUE THREAD

**Issue by obervinov** [obervinov/helm-charts#27]
**Describe the bug**
Reassigning `applyMethod in the context of a specific workspace does not work.
The value is taken only from the `global.agents` parameter.
https://github.com/obervinov/helm-charts/blob/main/src/terraform-operator-crds/templates/workspace.yaml#L23

**To Reproduce**
```yaml
      global:
        agent:
          applyMethod: manual
      workspaces:
        - name: dns
          description: "Manage the DNS records"
          workingDirectory: "dns"
          applyMethod: auto-approve
```
<img width="453" alt="Снимок экрана 2024-02-24 в 13 10 53" src="https://github.com/obervinov/helm-charts/assets/49606362/6946516d-7fc6-4d1c-903b-93d993cd0202">

**Expected behavior**
`applyMethod` specified in the context of a particular workspace should have higher priority and overwrite the value from `global.agents` for that workspace.
