### ISSUE TITLE
Universal-template: quotation mark escaping schedule

### ISSUE THREAD

**Issue by obervinov** [obervinov/helm-charts#34]
**Describe the bug**
https://github.com/obervinov/helm-charts/blob/v1.0.3/src/universal-template/templates/cronjobs.yaml#L34

**To Reproduce**
values.yaml
```yaml
applications:
  - name: backup-tools
    app:
      type: cronjob
      image:
        repository: "ghcr.io/obervinov/images/backup-tools"
        tag: "1.0.0"
        pullPolicy: IfNotPresent
        commands:
          - bash
        args:
          - -c
          - /scripts/backup.sh
      resources:
        requests:
          memory: "128Mi"
          cpu: null
        limits:
          memory: "256Mi"
          cpu: null
      cronJob:
        schedule: "*/1 * * * *"
        failedJobsHistoryLimit: 1
        successfulJobsHistoryLimit: 0
        restartPolicy: "OnFailure"
        ttlSecondsAfterFinished: 360
        activeDeadlineSeconds: 650
        backoffLimit: 1
        concurrencyPolicy: "Forbid"
        parallelism: 1
        completions: 1
```
```bash
apiVersion: batch/v1
kind: CronJob
metadata:
  name: release-name
  namespace: default
  labels:
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "release-name"
    app.kubernetes.io/version: "2.0.1"
    app: "release-name"
    version: "2.0.1"
    appselector: release-name
spec:
  schedule: */1 * * * *
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 0
  concurrencyPolicy: Forbid 
  jobTemplate:
    spec:
      parallelism: 1
      completions: 1
      backoffLimit: 1
      activeDeadlineSeconds: 650
      ttlSecondsAfterFinished: 360
      template:
        spec:
          containers:
          - name: release-name
            image: ghcr.io/obervinov/images/backup-tools:1.0.0
            imagePullPolicy: IfNotPresent
            resources:
              limits:
                cpu: null
                memory: 256Mi
              requests:
                cpu: null
                memory: 128Mi
          restartPolicy: OnFailure
...
Error: YAML parse error on universal-template/templates/cronjobs.yaml: error converting YAML to JSON: yaml: line 14: did not find expected alphabetic or numeric character
helm.go:84: [debug] error converting YAML to JSON: yaml: line 14: did not find expected alphabetic or numeric character
YAML parse error on universal-template/templates/cronjobs.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
	helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:146
helm.sh/helm/v3/pkg/releaseutil.SortManifests
	helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:106
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
	helm.sh/helm/v3/pkg/action/action.go:170
helm.sh/helm/v3/pkg/action.(*Install).RunWithContext
	helm.sh/helm/v3/pkg/action/install.go:262
main.runInstall
	helm.sh/helm/v3/cmd/helm/install.go:280
main.newTemplateCmd.func2
	helm.sh/helm/v3/cmd/helm/template.go:82
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.6.1/command.go:916
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.6.1/command.go:1044
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.6.1/command.go:968
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
	runtime/proc.go:250
runtime.goexit
	runtime/asm_amd64.s:1594
```

**Expected behavior**
None

**Screenshots**
None

**Additional context**
None
