### ISSUE TITLE
Universal-template: `affinity` and `nodeSelector` not provisioning in `cronJobs` and `Jobs`

### ISSUE THREAD

**Issue by obervinov** [obervinov/helm-charts#35]
**Describe the bug**
`Affinity` / `nodeSelector` parameters in `cronJob` and `job` bodies are not rendered.

**To Reproduce**
**values.yaml**
```yaml
applications:
  - name: backup-tools
    app:
      type: cronjob
      image:
        repository: "ghcr.io/obervinov/images/backup-tools"
        tag: "1.0.0"
        pullPolicy: IfNotPresent
        commands:
          - bash
        args:
          - -c
          - /scripts/backup.sh
      resources:
        requests:
          memory: "128Mi"
          cpu: null
        limits:
          memory: "256Mi"
          cpu: null
      nodeSelector:
        database: "true"
      tolerations:
        - key: projectsWorkload
          operator: Equal
          value: "true"
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: database
                  operator: In
                  values:
                    - "true"
      cronJob:
        schedule: '"*/1 * * * *"'
        failedJobsHistoryLimit: 1
        successfulJobsHistoryLimit: 0
        restartPolicy: "OnFailure"
        ttlSecondsAfterFinished: 360
        activeDeadlineSeconds: 650
        backoffLimit: 1
        concurrencyPolicy: "Forbid"
        parallelism: 1
        completions: 1
```

**Expected behavior**
The values of these parameters should be in the body of the cronjob.

**Screenshots**
<img width="915" alt="Снимок экрана 2024-04-15 в 18 30 13" src="https://github.com/obervinov/helm-charts/assets/49606362/63ca1dd4-e03d-4252-9b59-c5e478c05812">

**Additional context**
None
