### ISSUE TITLE
Universal-template: `ConfigMap` not working

### ISSUE THREAD

**Issue by obervinov** [obervinov/helm-charts#36]
**Describe the bug**
```bash
Error: template: universal-template/templates/configmaps.yaml:18:15: executing "universal-template/templates/configmaps.yaml" at <index . 1>: error calling index: value has type int; should be string
with helm_release.backup_job
on main.tf line 331, in resource "helm_release" "backup_job":
resource "helm_release" "backup_job" {
```

**To Reproduce**
**values.yaml**
```yaml
applications:
  - name: backup-tools
    app:
      type: cronjob
      image:
        repository: "ghcr.io/obervinov/images/backup-tools"
        tag: "1.0.0"
        pullPolicy: IfNotPresent
        commands:
          - bash
        args:
          - -c
          - /scripts/backup.sh
      resources:
        requests:
          memory: "128Mi"
          cpu: null
        limits:
          memory: "256Mi"
          cpu: null
      cronJob:
        schedule: '"*/60 * * * *"'
        failedJobsHistoryLimit: 1
        successfulJobsHistoryLimit: 3
        restartPolicy: "OnFailure"
        ttlSecondsAfterFinished: 360
        activeDeadlineSeconds: 650
        backoffLimit: 1
        concurrencyPolicy: "Forbid"
        parallelism: 1
        completions: 1
    configMap:
      mountPath: "/backups"
            - name: "backup.sh"
          data: |
            #!/bin/bash
            echo "--> Backup started at $(date) for database ..."
```

**Expected behavior**
None

**Screenshots**
None

**Additional context**
None
