### ISSUE TITLE
Universal-template: miss configuration between `volumeMounts` name and `persistentVolume` name

### ISSUE THREAD

**Issue by obervinov** [obervinov/helm-charts#39]
**Describe the bug**
```bash
77s         Warning   FailedCreate            statefulset/bot bot-0 in StatefulSet bot failed error: Pod "bot-0" is invalid: spec.containers[0].volumeMounts[0].name: Not found: "data"
```

**To Reproduce**
**values.yaml**
```yaml
applications:
  - name: ${local.project_name}
    app:
      type: statefulset
      replicas: 1
      image:
        repository: ghcr.io/obervinov/${local.project_name}
        tag: ${local.project_version}
        pullPolicy: Always
      extraLabels:
        app: ${local.project_name}
        version: ${local.project_version}
        env: ${local.project_environment}
      envs:
        - name: PROJECT_ENVIRONMENT
          value: "${local.project_environment}"
      resources:
        requests:
          memory: "150Mi"
        limits:
          memory: "300Mi"
      nodeSelector:
        python: "true"
      tolerations:
        - key: projectsWorkload
          operator: Equal
          value: "true"
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: python
                  operator: In
                  values:
                    - "true"
      persistentVolume:
        name: "data"
        size: 1Gi
        accessModes: ReadWriteOnce
        mountPath: "/home/${local.project_name}/data"
```

**Expected behavior**

**Screenshots**
None

**Additional context**
Need to add `appRefix`
- [x] https://github.com/obervinov/helm-charts/blob/v1.0.4/src/universal-template/templates/statefulsets.yaml#L109
- [x] https://github.com/obervinov/helm-charts/blob/v1.0.4/src/universal-template/templates/jobs.yaml#L95
- [x] https://github.com/obervinov/helm-charts/blob/v1.0.4/src/universal-template/templates/deployments.yaml#L125
- [x] https://github.com/obervinov/helm-charts/blob/v1.0.4/src/universal-template/templates/cronjobs.yaml#L101
