### ISSUE TITLE
Helm chart bug: Universal-template: wrong rbac examples

### ISSUE THREAD

**Issue by obervinov** [obervinov/helm-charts#44]
**Describe the bug**
Wrong `rbac` examples in `universal-template` helm chart.
Error message:
```yaml
    rbac:
      - rules:
          - apiGroups:
              - ""
            resources:
              - pods
            verbs:
              - get
```
```bash
Error: 2 errors occurred: * Role.rbac.authorization.k8s.io "minio-minio-kes" is invalid: [rules[0].verbs: Required value: verbs must contain at least one value, rules[0].apiGroups: Required value: resource rules must supply at least one api group, rules[0].resources: Required value: resource rules must supply at least one resource] * StatefulSet in version "v1" cannot be handled as a StatefulSet: json: cannot unmarshal bool into Go struct field EnvVar.spec.template.spec.containers.env.value of type string
```

**Additional context**
Information about where the bug is happening:
1. Helm chart name: universal-template
2. Helm chart version: 2.1.0
3. Template name: values.yaml

**Possible correction**
```yaml
    rbac:
      - apiGroups:
          - ""
        resources:
          - pods
        verbs:
          - get
```

**Screenshots**
None

**Check list after fixing the bug**
- [x] Fixed in `values.yaml`
- [x] Fixed in local documentation
