### ISSUE TITLE
Feature request: Add support for multiple containers and init containers to the Universal-template helm chart

### ISSUE THREAD

**Issue by obervinov** [obervinov/helm-charts#48]
**Is your feature request related to a problem? Please describe.**
Right now the chart limits the ability to render within a feed to only one container + init container. This makes the chart unsuitable for projects that require >1 container to be rendered within a feed.

**Describe the solution you'd like**
Add support for container arrays
```yaml
applications:
  - name: myapp
    app:
      type: statefulset
      replicas: 1
      initContainers:
        - name: init
          image:
            repository: alpine
            tag: "latest"
            commands:
              - /bin/sh
              - -c
            args:
              - whoami
          resources:
            requests:
              memory: "50Mi"
            limits:
              memory: "50Mi"
      containers:
        - name: container1
          image:
            repository: alpine
            tag: "latest"
            commands:
              - /bin/sh
              - -c
            args:
              - whoami
          resources:
            requests:
              memory: "50Mi"
            limits:
              memory: "50Mi"
        - name: container2
          image:
            repository: alpine
            tag: "latest"
            commands:
              - /bin/sh
              - -c
            args:
              - whoami
          resources:
            requests:
              memory: "50Mi"
            limits:
              memory: "50Mi"
```

**Describe alternatives you've considered**
None

**Additional context**
Since this feature introduces global changes to the values.yaml structure, this will be a major update.
