### ISSUE TITLE
Helm chart bug: Universal-template: ConfigMap is not mounted in pods after creation

### ISSUE THREAD

**Issue by obervinov** [obervinov/helm-charts#49]
**Describe the bug**
ConfigMap is not mounted in pods after creation in Universal-template helm chart.
Values.yaml:
```yaml
applications:
  - name: kes
    app:
      type: statefulset
      replicas: 1
      initContainer:
        name: kes-init
        image:
          repository: quay.io/minio/kes
          tag: "latest"
          commands:
            - /bin/sh
            - -c
          args:
            -  kes identity
        resources:
          requests:
            memory: "50Mi"
          limits:
            memory: "50Mi"
      image:
        repository: quay.io/minio/kes
        tag: latest
        args:
          - server
          - --config
          - /root/.minio/kes-config.yaml
      resources:
        requests:
          memory: "64Mi"
        limits:
          memory: "128Mi"
    configMap:
      mountPath: "/root/.minio"
      files:
        - name: kes-config.yaml
          data: |
            # https://github.com/minio/kes/blob/master/server-config.yaml
            address: "0.0.0.0:7373"
            admin:
              identity: disabled
            tls:
              key: /kes-credentials/private.key
              cert: /kes-credentials/public.crt
```

**Additional context**
Information about where the bug is happening:
1. Helm chart name: Universal-template
2. Helm chart version: 2.1.0
3. Template name: `_volumes.tpl`

**Possible correction**
None

**Screenshots**
None

**Check list after fixing the bug**
- [ ] ConfigMap is rendered correctly in the volumes section of the controller app
