### ISSUE TITLE
Feature request: Add to support `securityContext` for containers in Unisersal-template helm chart

### ISSUE THREAD

**Issue by obervinov** [obervinov/helm-charts#53]
**Is your feature request related to a problem? Please describe.**
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kes-server
  namespace: your-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kes-server
  template:
    metadata:
      labels:
        app: kes-server
    spec:
      containers:
      - name: kes-server
        image: your-kes-image
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
```

**Describe the solution you'd like**
Add a simple `toYaml` for the `securityContext: ...` block, this will allow flexibility in patch management and not add support for different securityContext separate issues

**Describe alternatives you've considered**
None

**Additional context**
None
