### ISSUE TITLE
Feature request: add support for specifying the service port by name in Ingress (universal-template chart)

### ISSUE THREAD

**Issue by obervinov** [obervinov/helm-charts#74]
**Is your feature request related to a problem? Please describe.**
The Popeye utility recommends using port names instead of numbers. It will also make it easier to specify ports in `values.yaml`.
```bash
[POP-1403] Ingress backend uses a port#, prefer a named port: 8080
```

**Describe the solution you'd like**
Both specification support (name or number)
```yaml
  rules:
    - host: app.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-svc
                port:
                  name: http
```
```yaml
  rules:
    - host: app.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-svc
                port:
                  number: 8080
```

**Describe alternatives you've considered**
None

**Additional context**
Nonde
